In [ ]:
import numpy as np
import time

my_list = list(range(1_000_000))
start_time = time.time()
result_list = [x * 2 for x in my_list]
end_time = time.time()
print(f"파이썬 리스트 실행 시간: {end_time - start_time:.5f}초")

my_array = np.arange(1_000_000)
start_time = time.time()
result_array = my_array * 2
end_time = time.time()
print(f"넘파이 배열 실행 시간: {end_time - start_time:.5f}초")


파이썬 리스트 실행 시간: 0.09756초
넘파이 배열 실행 시간: 0.00739초


In [ ]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)


[[1 2 3]
 [4 5 6]]


In [ ]:
a = np.array([10, 20, 30, 40, 50])
condition_mask = (a > 25)
filtered_array = a[condition_mask]
print(filtered_array)

[30 40 50]


In [ ]:
distances = np.array([1, 2, 3, 5, 8])

windspeeds = np.array([0, 5, 10, 7, 12])

base_usage_rate = 10

additional_usage_rate = windspeeds

total_usage_rate = base_usage_rate + additional_usage_rate

battery_consumption = distances * total_usage_rate

print("비행 거리 (km):", distances)
print("풍속 (m/s):", windspeeds)
print("총 소모율 (%/km):", total_usage_rate)
print("예상 배터리 소모량 (%):", battery_consumption)

비행 거리 (km): [1 2 3 5 8]
풍속 (m/s): [ 0  5 10  7 12]
총 소모율 (%/km): [10 15 20 17 22]
예상 배터리 소모량 (%): [ 10  30  60  85 176]
